#!/bin/bash
set -o nounset
set -o errexit
set +o histexpand

echo "git reset/pull..."
git reset --hard HEAD
GIT_BRANCH=$(git symbolic-ref --short -q HEAD)
timeout 120s git fetch --all --prune
git reset --hard "origin/$GIT_BRANCH"
echo "Branch $GIT_BRANCH"
timeout 60s git submodule foreach --recursive git pull origin "$GIT_BRANCH"

bbdeployor/make_project
bbdeployor/install_project
